

export const employees = [
{
id: 1,
name: "Adebayo Okafor",
title: "HR Director",
salary: 5800,
phone: "080-33445566",
email: "adebayo@sonak.com",
animal: "Lion",
startDate: "2015-06-15",
location: "Lagos",
department: "Human Resources",
skills: ["Strategic Planning", " Recruitment"]
},
{
id: 2,
name: "Chioma Eze",
title: "IT Manager",
salary: 5200,
phone: "081-77889900",
email: "chioma@sonak.com",
animal: "Panther",
startDate: "2018-03-22",
location: "Abuja",
department: "Information Technology",
skills: ["Cybersecurity", " Cloud Computing"]
},
{
id: 3,
name: "Emeka Nwachukwu",
title: "Finance Controller",
salary: 5400,
phone: "070-11223344",
email: "emeka@sonak.com",
animal: "Elephant",
startDate: "2009-11-05",
location: "Port Harcourt",
department: "Finance",
skills: ["Accounting", " Risk Management"]
},
{
id: 4,
name: "Folake Adeleke",
title: "Marketing Director",
salary: 5600,
phone: "090-55667788",
email: "folake@sonak.com",
animal: "Peacock",
startDate: "2024-10-18",
location: "Ibadan",
department: "Marketing",
skills: ["Marketing", " Brand Strategy"]
},
{
id: 5,
name: "Ibrahim Mohammed",
title: "Operations Manager",
salary: 5100,
phone: "080-99001122",
email: "ibrahim@sonak.com",
animal: "Eagle",
startDate: "2021-02-14",
location: "Kano",
department: "Operations",
skills: ["Supply Chain", " Logistics"]
},
{
id: 6,
name: "Ngozi Onyema",
title: "Legal Counsel",
salary: 6000,
phone: "081-33445577",
email: "ngozi@sonak.com",
animal: "Owl",
startDate: "2014-08-30",
location: "Enugu",
department: "Legal",
skills: ["Corporate Law", " Negotiation"]
},
{
id: 7,
name: "Oluwaseun Balogun",
title: "Head of Engineering",
salary: 6200,
phone: "070-88990011",
email: "seun@sonak.com",
animal: "Rhino",
startDate: "2013-05-12",
location: "Lagos",
department: "Engineering",
skills: ["SW Development", " Architecture"]
},
{
id: 8,
name: "Amina Yusuf",
title: "Customer Experience Lead",
salary: 4800,
phone: "090-22334455",
email: "amina@sonak.com",
animal: "Dolphin",
startDate: "2020-01-25",
location: "Kaduna",
department: "Customer Service",
skills: ["Innovation", " Service Design"]
},
{
id: 9,
name: "Chinedu Okoro",
title: "Data Scientist",
salary: 5300,
phone: "080-66778899",
email: "chinedu@sonak.com",
animal: "Wolf",
startDate: "2021-07-08",
location: "Abuja",
department: "Data Analytics",
skills: ["Machine Learning", " Big Data"]
},
{
id: 10,
name: "Yemisi Adebayo",
title: "Head of Design",
salary: 5100,
phone: "081-44556677",
email: "yemisi@sonak.com",
animal: "Butterfly",
startDate: "2025-10-17",
location: "Lagos",
department: "Creative",
skills: ["Product Design", " Design Thinking"]
}
];
